version: '3'

networks:
  knowme_network:
    driver: bridge
    name: knowme_network

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - knowme_network
    env_file: .env
    ports:
      - '3000:3000'
    volumes:
      - .:/srv/app
      - /srv/app/node_modules
    links:
      - mongodb
  mongodb:
    image: mongo:latest
    networks:
      knowme_network:
    environment:
      - MONGODB_DATABASE="knowme_db"
    ports:
      - 27017:27017
    volumes:
      - knowme:/data/db
volumes:
  knowme:
